name: CI
on: 
  pull_request:
    branches: [develop-one]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v1
      - name: Use NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"

      - run: npm ci
      - run: npm format:check
      - run: npm test -- --codecoverage
        env:
          CI: true
          



